AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamoOperations

  Sample SAM Template for DynamoOperations

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: python3.8
    Environment:
      Variables:
        TABLE_NAME: Files
        ENDPOINT_URL: http://192.168.240.1:8000

Resources:
  DynamoOperationsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dynamo_operations/
      Handler: app.lambda_handler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /dynamo/save
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/dynamo/"
  DynamoOperationsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DynamoOperationsFunction.Arn
  DynamoOperationsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DynamoOperationsFunctionRole.Arn
